# Generated by Django 3.1.1 on 2020-09-16 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=100)),
                ('video_title', models.TextField()),
                ('video_description', models.TextField()),
                ('channel_title', models.CharField(max_length=200)),
                ('video_thumbnail', models.TextField()),
                ('video_publish_date', models.DateTimeField()),
            ],
        ),
    ]
